### ISSUE TITLE
GoBuilder builds failing

### ISSUE THREAD

**Issue by Luzifer** [myrkvi/ve#1]
Hey there,

I saw your build having a hard time on GoBuilder because you're using CGO bindings. While CGO is by default disabled but you can add a configuration directive to your `.gobuilder.yml` file to enable it: `allow_cgo: true`.

So your `.gobuilder.yml` file would be changed as following:

``` yaml
build_matrix:
    windows:
    darwin:
    linux/amd64:
    linux/386:
allow_cgo: true
```

Though I'm not a 100% sure whether it will work afterwards because maybe not all required C libraries are present on the build system.
